# nginx proxy address - http://172.17.0.1:3004

name: rallly
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  rallly:
    image: lukevella/rallly:latest
    pull_policy: always
    container_name: rallly-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - rallly
    ports:
      - "172.17.0.1:3004:3000"
    environment:
      TZ: ${TZ:-America/New_York}
      BASE_URL: https://${BASE_HOST_NAME:-localhost}.${BASE_DOMAIN_NAME:-example.com}
      SECRET_PASSWORD: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
      DATABASE_URL: postgresql://${DB_USER_NAME:-rallly}:${DB_USER_PASS:-changeme_db_password}@rallly-db:5432/${DB_CREATE_DATABASE_NAME:-rallly}
      SUPPORT_EMAIL: ${APP_ADMIN_USER:-admin@example.com}
      SMTP_HOST: ${EMAIL_SERVER_HOST:-localhost}
      SMTP_PORT: ${EMAIL_SERVER_PORT:-587}
      SMTP_USER: ${EMAIL_SERVER_USER:-""}
      SMTP_PWD: ${EMAIL_SERVER_PASS:-""}
      NOREPLY_EMAIL: ${EMAIL_SERVER_MAIL_FROM:-noreply@example.com}
      DISABLE_LANDING_PAGE: ${DISABLE_LANDING_PAGE:-true}
    depends_on:
      rallly-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  rallly-db:
    image: postgres:latest
    pull_policy: always
    container_name: rallly-db
    restart: always
    logging: *default-logging
    networks:
      - rallly
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-rallly}
      POSTGRES_USER: ${DB_USER_NAME:-rallly}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - ./volumes/data/db/postgres/rallly:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_NAME:-rallly} -d ${DB_CREATE_DATABASE_NAME:-rallly}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  rallly:
    name: rallly
    external: false
